apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-box
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: development-box
  template:
    metadata:
      labels:
        app: development-box
    spec:
      containers:
      - name: development-box
        image: entropypool/development-box:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: PATH
          value: "/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin"
        - name: GOPROXY
          value: "https://goproxy.cn,direct"
        command: ["/usr/sbin/sshd", "-d"]

---
apiVersion: v1
kind: Service
metadata:
  name: development-box
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    nodePort: 22222
    name: ssh
    protocol: TCP
  selector:
    app: development-box
